import { DomainEntity } from 'domain-objects';

import { UnixEndpoint } from './UnixEndpoint';

/**
 * .what = a declarative structure which represents a unix port alias (port forwarding)
 * .why = enables declarative management of systemd-socat services following declastruct patterns
 */
export interface DeclaredUnixPortAlias {
  /**
   * .what = systemd service unit file path
   * .note = @metadata -> only known after persistence, autogenerated
   */
  uri?: string;

  /**
   * .what = mechanism used to manage the port forwarding
   * .note = currently only 'systemd-socat' is supported
   */
  via: 'systemd-socat';

  /**
   * .what = source endpoint to listen on
   */
  from: UnixEndpoint;

  /**
   * .what = target endpoint to forward to
   */
  into: UnixEndpoint;
}

export class DeclaredUnixPortAlias
  extends DomainEntity<DeclaredUnixPortAlias>
  implements DeclaredUnixPortAlias
{
  // TODO: add primary = ['uri'] once declastruct supports optional metadata as primary key
  public static unique = ['via', 'from'] as const;
  public static nested = {
    from: UnixEndpoint,
    into: UnixEndpoint,
  };

  /**
   * .what = intrinsic attributes resolved from persistence, not user-settable
   * .why = `uri` (the systemd unit path) is autogenerated on apply and read back
   *        on get. it must be excluded from the equivalence diff, else a re-plan
   *        always sees remote.uri vs desired(undefined) and reports a false
   *        UPDATE - a break of idempotency (mirrors keypair.publicKey)
   */
  public static readonly = ['uri'] as const;
}
