import { DomainEntity, DomainLiteral } from 'domain-objects';

/**
 * .what = endpoint specification for port forwarding
 * .why = reusable structure for source and target endpoints
 */
export interface UnixPortEndpoint {
  host: string;
  port: number;
}

export class UnixPortEndpoint
  extends DomainLiteral<UnixPortEndpoint>
  implements UnixPortEndpoint {}

/**
 * .what = a declarative structure which represents a unix port alias (port forwarding)
 * .why = enables declarative management of systemd-socat services following declastruct patterns
 */
export interface DeclaredUnixPortAlias {
  /**
   * .what = systemd service unit file path
   * .note = @metadata -> only known after persistence, autogenerated
   */
  uri?: string;

  /**
   * .what = mechanism used to manage the port forwarding
   * .note = currently only 'systemd-socat' is supported
   */
  via: 'systemd-socat';

  /**
   * .what = source endpoint to listen on
   */
  from: UnixPortEndpoint;

  /**
   * .what = target endpoint to forward to
   */
  into: UnixPortEndpoint;
}

export class DeclaredUnixPortAlias
  extends DomainEntity<DeclaredUnixPortAlias>
  implements DeclaredUnixPortAlias
{
  // TODO: add primary = ['uri'] once declastruct supports optional metadata as primary key
  public static unique = ['via', 'from'] as const;
  public static nested = {
    from: UnixPortEndpoint,
    into: UnixPortEndpoint,
  };
}
